### ISSUE TITLE
Move the README to root of the repo

### ISSUE THREAD

**Issue by alex-nitrokey** [d-e-s-o/nitrocli#19]
I think the [/nitrocli/README.md](https://github.com/d-e-s-o/nitrocli/blob/master/nitrocli/README.md) is more useful in the main folder, what do you think?

**Comment by d-e-s-o** [comment]
Hi Alex! Thanks for your comment. I'd rather not change the location of the `README`. It conceptually belongs to the crate itself, and that resides in the `nitrocli` sub-folder. Moving it out there would also likely screw things up for [`crates.io`](https://crates.io/crates/nitrocli) (although that likely can be configured).

You should be able to directly navigate to the `nitrocli` sub-folder via `https://github.com/d-e-s-o/nitrocli/tree/master/nitrocli`. The `master` branch is where development will stay and so this link should be stable.

I understand that unconditionally having a proper landing would be better, but that is not possible with the way dependencies are managed. There has been some discussion around that in issue #5, but right now there are no plans for changing that layout.

Does that make sense to you? Does that question have a deeper cause or are you just asking out of curiosity?

**Comment by alex-nitrokey** [comment]
Hi,

thanks for the explanation! I wasn't aware, that this would affect the project in this ways. I just thought a kind of "greeting" README.md would make sense for interested users. I did not fully understand: does this also apply to an *additional* README.md in the root folder?

Anyway I trust your assessment in this :smile:

**Comment by d-e-s-o** [comment]
Allow me to close this issue and leave the README where it is right now. The file would be moved if I ever decided that I no longer want to vendor dependencies the way I do right now. For better or worse, for now we have what we have :D

Nevertheless, please use the [direct link](https://github.com/d-e-s-o/nitrocli/tree/master/nitrocli) where appropriate in order to link to the project!

**Comment by jans23** [comment]
Would it be possible to add a README which links to the actual README?

**Comment by d-e-s-o** [comment]
In principle that would be possible, but due to the way dependencies are organized and managed any file there would cause problems. The way [`git-subrepo`](https://github.com/d-e-s-o/git-subrepo/tree/devel/git-subrepo) -- which I use to manage dependecies -- works is by organizing the individual dependencies in folders in the repository root. If we add a file there, that will violate this contract, because from the program's perspective, it does not belong to any of the "subrepos".
The way I look at it is that the `nitrocli/` subfolder is the relevant part (and if you navigate to [`crates.io`](https://crates.io/crates/nitrocli) that relevant part is exactly what you see). The rest is supporting code. It is unfortunate that this cannot be expressed well on Github in that I can't make the user directly navigate to the folder of interest, but that is a trade-off we have to live with right now.
