### ISSUE TITLE
Not building anymore

### ISSUE THREAD

**Issue by Unb9rn** [d-e-s-o/nitrocli#94]
I was trying to build latest nitrocli version on Arch Linux. It would fail with following error:
unnecessary trailing semicolon in macros.rs:131:21
$($body);*
error: could not compile 'libc'.
and a bunch of warnings regarding deprecation of cargo's use_std feature.

**Comment by d-e-s-o** [comment]
The issue seems to be in `libc` itself and has nothing to do with `nitrocli`. In fact, it even exists on `devel`. An upgrade to `0.2.66` (from `0.2.62`) resolves it.

@robinkrahl used to maintain the Arch Linux build.

**Comment by d-e-s-o** [comment]
I suspect (but haven't verified) that it got introduced with a newer version of Rust. Newer versions sometimes add new lints or change the behavior of existing ones in unexpected ways. This may be the case here and that's why `deny(warnings)` is extremely dangerous and I [removed that](https://github.com/d-e-s-o/nitrocli/commit/1d62e9151369ab50d98d638e80753630c0c3cbbf) from this crate's code base.
That is a long winded way of saying that you may get lucky using an older version of Rust.

**Comment by robinkrahl** [comment]
I performed some tests:
- `cargo install` works with stable/1.39.0 ([log](https://builds.sr.ht/~ireas/job/123412)).
- `cargo build` on master fails with 1.39.0 ([log](https://builds.sr.ht/~ireas/job/123414)) but works with 1.38.0 ([log](https://builds.sr.ht/~ireas/job/123419)).

`libc` fixed the problem with [this commit](https://github.com/rust-lang/libc/commit/3241ec58085a2256b88be01efa505c0509f89ce0) (version 0.2.63).

Conclusion:  Use rustc 1.38.0, use `cargo install` instead of `cargo build`, update the `libc` dependency to at least 0.2.63 or compile from devel instead of master.

**Comment by d-e-s-o** [comment]
Thanks Robin. I've just released [`0.3.0`](https://github.com/d-e-s-o/nitrocli/releases/tag/v0.3.0) which uses the new `nitrokey` release which in turn should prevent this build failure on Rust `1.39`. Feel free to push it into AUR if you have the cycles.

**Comment by robinkrahl** [comment]
I’ve just updated the AUR build to 0.3.0-1.

**Comment by d-e-s-o** [comment]
Awesome! Thanks Robin! I don't see anything else to be done here then. Closing.
